import '../styles/globals.css'
import type {AppProps} from 'next/app'
import Head from 'next/head'
import { AccountsProvider } from '../hooks/AccountsProvider'

function MyApp({Component, pageProps}: AppProps) {
  return (
    <>
      <Head>
        <title>Create Next polkadot App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <AccountsProvider>
        <Component {...pageProps} />
      </AccountsProvider>
    </>

  )
}

export default MyApp
